apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: sc-pv
  volumes:
    - name: sc-pv
      persistentVolumeClaim:
        claimName: pvc-2
        