apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  selector:
    matchLabels:
      app: portal-noticias
  replicas: 3
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 # De quando enquanto tempo eu quero fazer essa validação
            failureThreshold: 3 # Nº máximo de falhas que eu toleto antes de executar o reinício desse container
            initialDelaySeconds: 20  # A partir de quanto eu quero que seja executada a primeira validação

     