apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  serviceName: svc-sistema-noticias # Nome específico do serviço que gerenciará esses StatefulSet
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias
  template:
    metadata:
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: sistema-noticias-container
        image: aluracursos/sistema-noticias:1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: sistema-configmap
        volumeMounts:
          - mountPath: /var/www/html/uploads
            name: imagens
          - mountPath: /tmp
            name: sessao
        livenessProbe:
              httpGet:
                path: /
                port: 80
              periodSeconds: 10 # De quando enquanto tempo eu quero fazer essa validação
              failureThreshold: 3 # Nº máximo de falhas que eu toleto antes de executar o reinício desse container
              initialDelaySeconds: 20  # A partir de quanto eu quero que seja executada a primeira validação
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
